"""
modules/export.py
Generates downloadable HTML and PDF reports from chart collections.
"""

import os
import datetime
import tempfile
import plotly.io as pio
from fpdf import FPDF


def generate_html_report(charts, session_name):
    """Standalone interactive HTML using Plotly CDN."""
    html = f"""
    <html>
    <head>
        <title>{session_name} - DataLyze</title>
        <style>
            body {{ font-family: 'Inter', sans-serif; padding: 2rem; max-width: 1200px; margin: auto; color: #333; }}
            h1 {{ color: #4f6ef7; text-align: center; }}
            .chart-container {{ margin-bottom: 3rem; padding: 1rem; border: 1px solid #eee; border-radius: 12px; }}
            .notes {{ background: #f8fafc; padding: 1rem; border-left: 4px solid #8b5cf6; margin-top: 1rem; }}
        </style>
    </head>
    <body>
        <h1>📊 {session_name}</h1>
        <hr>
    """
    for uid, title, fig, notes in charts:
        html += f"<div class='chart-container'><h2>{title}</h2>"
        html += fig.to_html(full_html=False, include_plotlyjs='cdn')
        if notes:
            html += f"<div class='notes'><b>📝 Notes:</b> {notes}</div>"
        html += "</div>"
    html += "</body></html>"
    return html


def generate_pdf_report(charts, session_name):
    """
    Static PDF via FPDF2 + Kaleido.
    Requirements: pip install fpdf2 kaleido
    """
    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    def _safe(text):
        return str(text).encode("latin-1", "replace").decode("latin-1")

    pdf.set_font("helvetica", "B", 20)
    pdf.cell(0, 15, _safe(session_name), align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", "", 10)
    pdf.cell(0, 8,
             _safe(f"Generated by DataLyze  ·  {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}"),
             align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(8)

    for uid, title, fig, notes in charts:
        pdf.set_font("helvetica", "B", 13)
        pdf.cell(0, 10, _safe(title), new_x="LMARGIN", new_y="NEXT")
        try:
            raw = pio.to_image(fig, format="png", width=900, height=500, scale=1.5)
            img_bytes = bytes(raw)
            with tempfile.NamedTemporaryFile(delete=False, suffix=".png") as tmp:
                tmp.write(img_bytes)
                tmp_path = tmp.name
            pdf.image(tmp_path, w=190)
            os.remove(tmp_path)
        except Exception as e:
            pdf.set_font("helvetica", "I", 10)
            pdf.cell(0, 8, _safe(f"[Chart unavailable: {e}]"), new_x="LMARGIN", new_y="NEXT")

        if notes:
            pdf.set_font("helvetica", "I", 10)
            pdf.set_fill_color(248, 250, 252)
            pdf.multi_cell(0, 7, _safe(f"Notes: {notes}"), fill=True)
        pdf.ln(8)

    return bytes(pdf.output())
